kind = "funnel"

[[items]]
label = "Stage 1"
[[items]]
label = "Stage 2"
[[items]]
label = "Stage 3"
[[items]]
label = "Stage 4"
[[items]]
label = "Stage 5"
[[items]]
label = "Stage 6"
[[items]]
label = "Stage 7"
[[items]]
label = "Stage 8"
[[items]]
label = "Stage 9"
[[items]]
label = "Stage 10"
[[items]]
label = "Stage 11"
