[package]
name = "declart-cli"
version = "0.11.0"
edition = "2021"

[[bin]]
name = "declart"
path = "src/main.rs"

[dependencies]
declart-core = { path = "../declart-core" }
clap = { version = "4", features = ["derive"] }
anyhow = "1"
resvg = { version = "0.47.0", default-features = false, features = ["text", "system-fonts"] }
notify = "8.2.0"
